// Generated by CoffeeScript 1.7.1

/*
  NOTE: this is just a nodejs script for sending messages to PubNub, not a real server
 */

(function() {
  var PUBNUB, channel, message;

  PUBNUB = require("pubnub").init({
    publish_key: "pub-c-f628756e-3c83-4331-884f-f3bc1c4da7c0",
    subscribe_key: "sub-c-2a902b72-04f7-11e6-bbd9-02ee2ddab7fe",
    uuid: "Raul" + Math.floor(Math.random() * 1000)
  });

  channel = process.argv[2];

  message = process.argv[3];

  console.log("sending " + (JSON.stringify(message)) + " to #" + channel);

  PUBNUB.publish({
    channel: channel,
    message: message,
    callback: function() {
      console.log("message sent.");
      return process.exit();
    }
  });

}).call(this);
